import React, { useState, useEffect } from 'react';
import { Search, Terminal, Activity, Layers, Menu, X, Command, PanelLeftClose, PanelLeftOpen, ShieldCheck } from 'lucide-react';
import { MatchList } from './components/MatchList';
import { MatchDashboard } from './components/MatchDashboard';

const LEAGUES = [
  { id: 'ALL', name: 'Toutes les Ligues', code: 'ALL', flag: '🌍' },
  { id: 'EDV', name: 'Eredivisie', code: 'EDV', flag: '🇳🇱' },
  { id: 'PL', name: 'Premier League', code: 'PL', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { id: 'POR1', name: 'Primeira Liga', code: 'POR1', flag: '🇵🇹' },
  { id: 'LIGA', name: 'LaLiga', code: 'LIGA', flag: '🇪🇸' },
  { id: 'LIG1', name: 'Ligue 1', code: 'LIG1', flag: '🇫🇷' },
  { id: 'BUND', name: 'Bundesliga', code: 'BUND', flag: '🇩🇪' },
  { id: 'SERIEA', name: 'Serie A', code: 'SERIEA', flag: '🇮🇹' },
];

export default function App() {
  const [selectedLeague, setSelectedLeague] = useState(LEAGUES[0]);
  const [selectedDate, setSelectedDate] = useState('ALL');
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedMatch, setSelectedMatch] = useState(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [matchListOpen, setMatchListOpen] = useState(true);
  const [showTrueFavorites, setShowTrueFavorites] = useState(false);

  useEffect(() => {
    async function fetchData() {
      setLoading(true);
      setError(null);
      try {
        // 1. Load the dynamic index.json generated by our Vite plugin
        const indexResponse = await fetch('/data/index.json').catch(() => null);
        let availableFiles = [];
        if (indexResponse && indexResponse.ok) {
          availableFiles = await indexResponse.json();
        }

        // 2. Find matching files for the selected league
        const code = selectedLeague.code;
        
        let json = { matches: [] };
        
        if (code === 'ALL') {
          let allMatches = [];
          const leagueCodes = LEAGUES.filter(l => l.code !== 'ALL').map(l => l.code);
          
          const fetchPromises = leagueCodes.map(async (c) => {
            const matchingFiles = availableFiles.filter(f => f.includes(`-${c}_`));
            matchingFiles.sort().reverse();
            const targetFile = matchingFiles.length > 0 ? `/data/${matchingFiles[0]}` : `/data/LATEST_${c}.json`;
            try {
              const res = await fetch(targetFile);
              if (res.ok) {
                const data = await res.json();
                return data.matches || [];
              }
            } catch(e) {}
            return [];
          });
          
          const results = await Promise.all(fetchPromises);
          results.forEach(m => allMatches.push(...m));
          json.matches = allMatches;
        } else {
          const matchingFiles = availableFiles.filter(f => f.includes(`-${code}_`));
          matchingFiles.sort().reverse();
          const targetFile = matchingFiles.length > 0 ? `/data/${matchingFiles[0]}` : `/data/LATEST_${code}.json`;
          
          const response = await fetch(targetFile);
          if (!response.ok) {
            throw new Error(`Data matrix not found for ${selectedLeague.name}.`);
          }
          json = await response.json();
        }

        // Fetch matchups to get dates
        try {
          const [matchupA, matchupB] = await Promise.all([
            fetch('/data/matchups/Matchups_Week-A04-Avril.json').then(res => res.ok ? res.json() : null),
            fetch('/data/matchups/Matchups_Week-B04-Avril.json').then(res => res.ok ? res.json() : null)
          ]);
          
          let allMatchups = [];
          if (matchupA) Object.values(matchupA).forEach(arr => allMatchups.push(...arr));
          if (matchupB) Object.values(matchupB).forEach(arr => allMatchups.push(...arr));

          const ALIASES = {
            "m'gladbach": "monchengladbach",
            "hsv": "hamburger sv",
            "man utd": "manchester united",
            "man city": "manchester city",
            "forest": "nottingham forest",
            "psg": "paris saint-germain",
            "atl. madrid": "atletico madrid",
            "paris": "paris saint-germain",
            "sporting": "sporting cp"
          };
          
          const normalize = (str) => str.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim();
          
          const getAlias = (name) => {
            const norm = normalize(name);
            return ALIASES[norm] || norm;
          };

          if (json.matches) {
            json.matches.forEach(m => {
              const parts = m.Matchup.split(' vs ');
              if (parts.length === 2) {
                const mHome = normalize(parts[0]);
                const mAway = normalize(parts[1]);
                
                const found = allMatchups.find(mu => {
                  const muHome = getAlias(mu.home);
                  const muAway = getAlias(mu.away);
                  
                  const homeMatch = mHome.includes(muHome) || muHome.includes(mHome);
                  const awayMatch = mAway.includes(muAway) || muAway.includes(mAway);
                  
                  return homeMatch && awayMatch;
                });
                m.date = found ? found.date : 'Date Inconnue';
              } else {
                m.date = 'Date Inconnue';
              }
            });
          }
        } catch (err) {
          console.error("Failed to merge dates:", err);
        }

        setData(json);
        setSelectedMatch(null);
      } catch (err) {
        console.error(err);
        setError(err.message);
        setData(null);
        setSelectedMatch(null);
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, [selectedLeague]);

  const availableDates = Array.from(new Set(data?.matches?.map(m => m.date || 'Date Inconnue') || [])).sort((a, b) => {
    if (a === 'Date Inconnue') return 1;
    if (b === 'Date Inconnue') return -1;
    return a.localeCompare(b);
  });

  const filteredMatches = data?.matches?.filter(match => {
    const textMatch = match.Matchup.toLowerCase().includes(searchQuery.toLowerCase());
    const dateMatch = selectedDate === 'ALL' || match.date === selectedDate;
    const isFalseFav = match.Risk_Management_Context?.Tactical_Red_Flags?.IS_FALSE_FAVORITE;
    const favMatch = !showTrueFavorites || isFalseFav === false;
    return textMatch && dateMatch && favMatch;
  }) || [];

  return (
    <div className="flex h-screen overflow-hidden bg-slate-950 text-slate-200">
      {/* Mobile Sidebar Overlay */}
      {sidebarOpen && (
        <div 
          className="fixed inset-0 bg-black/60 z-20 lg:hidden backdrop-blur-sm transition-opacity"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      {/* Sidebar */}
      <aside className={`
        fixed lg:static inset-y-0 left-0 z-30
        w-64 bg-slate-900 border-r border-slate-800 flex flex-col
        transition-transform duration-300 ease-in-out shadow-2xl lg:shadow-none
        ${sidebarOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'}
      `}>
        <div className="p-5 flex items-center gap-3 border-b border-slate-800 bg-slate-900/50">
          <div className="bg-emerald-500/10 p-2 rounded-lg border border-emerald-500/20 shadow-inner">
            <Terminal className="text-emerald-400" size={20} />
          </div>
          <div>
            <h1 className="font-bold text-sm text-slate-100 tracking-wide">ColdBetdrox Lab</h1>
            <p className="text-[10px] text-slate-500 font-mono tracking-widest uppercase">Terminal v7.6.1</p>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
          <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-3 px-2">Matrices Actives</div>
          <nav className="flex flex-col gap-1.5">
            {LEAGUES.map(league => (
              <button
                key={league.id}
                onClick={() => {
                  setSelectedLeague(league);
                  setSidebarOpen(false);
                  setMatchListOpen(true);
                }}
                className={`
                  flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm transition-all text-left
                  ${selectedLeague.id === league.id 
                    ? 'bg-slate-800 text-emerald-400 font-medium shadow-sm ring-1 ring-slate-700/50' 
                    : 'text-slate-400 hover:bg-slate-800/50 hover:text-slate-200'}
                `}
              >
                <span className="text-lg">{league.flag}</span>
                {league.name}
              </button>
            ))}
          </nav>
        </div>
        
        <div className="p-4 border-t border-slate-800 flex flex-col gap-1">
          <div className="flex items-center gap-2 text-[10px] text-slate-500 font-mono">
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></div>
            SYSTÈME EN LIGNE
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col min-w-0 bg-slate-950">
        {/* Header */}
        <header className="h-16 border-b border-slate-800 bg-slate-900/80 backdrop-blur-md flex items-center justify-between px-4 lg:px-6 sticky top-0 z-10">
          <div className="flex items-center gap-4">
            <button 
              className="lg:hidden text-slate-400 hover:text-slate-200 transition-colors bg-slate-800 p-2 rounded-lg border border-slate-700"
              onClick={() => setSidebarOpen(true)}
            >
              <Menu size={18} />
            </button>
            <button 
              className="hidden lg:flex text-slate-400 hover:text-slate-200 transition-colors bg-slate-900 p-2 rounded-lg border border-slate-800"
              onClick={() => setMatchListOpen(!matchListOpen)}
              title={matchListOpen ? "Masquer la liste des matchs" : "Afficher la liste des matchs"}
            >
              {matchListOpen ? <PanelLeftClose size={18} /> : <PanelLeftOpen size={18} />}
            </button>
            <div className="hidden lg:flex items-center gap-2 text-xs text-slate-400 font-medium uppercase tracking-widest bg-slate-900 px-3 py-1.5 rounded-lg border border-slate-800">
              <Activity size={14} className="text-emerald-500" />
              <span>Engine <span className="text-emerald-400 font-mono ml-1">ACTIVE</span></span>
            </div>
          </div>

          <div className="flex-1 max-w-lg ml-4 lg:ml-0 flex items-center gap-2">
            <div className="relative group flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500 group-focus-within:text-emerald-500 transition-colors" size={16} />
              <input 
                type="text" 
                placeholder="Filtrer les matchs..."
                value={searchQuery}
                onChange={e => setSearchQuery(e.target.value)}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg py-2 pl-9 pr-4 text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 transition-all font-mono"
              />
            </div>
            <select 
              value={selectedDate}
              onChange={e => setSelectedDate(e.target.value)}
              className="bg-slate-950 border border-slate-700 rounded-lg py-2 px-3 text-sm text-slate-400 focus:outline-none focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 transition-all font-mono appearance-none min-w-[140px] cursor-pointer"
            >
              <option value="ALL">Toutes les dates</option>
              {availableDates.map(date => {
                let displayDate = date;
                if (date !== 'Date Inconnue') {
                  const d = new Date(`${date}T12:00:00`);
                  displayDate = d.toLocaleDateString('fr-FR', { weekday: 'short', day: 'numeric', month: 'short' });
                  displayDate = displayDate.charAt(0).toUpperCase() + displayDate.slice(1);
                }
                return (
                  <option key={date} value={date}>
                    {displayDate}
                  </option>
                );
              })}
            </select>
            <button
              onClick={() => setShowTrueFavorites(!showTrueFavorites)}
              className={`flex items-center gap-2 px-3 py-2 rounded-lg text-sm transition-all font-mono border ${
                showTrueFavorites 
                  ? 'bg-emerald-500/10 border-emerald-500/50 text-emerald-400 shadow-inner' 
                  : 'bg-slate-950 border-slate-700 text-slate-400 hover:text-slate-200'
              }`}
              title="Afficher uniquement les vrais favoris"
            >
              <ShieldCheck size={16} className={showTrueFavorites ? 'text-emerald-400' : 'text-slate-500'} />
              <span className="hidden sm:inline text-xs">{showTrueFavorites ? 'Vrais Favoris' : 'Vrais Favoris'}</span>
            </button>
          </div>
        </header>

        {/* Content Area */}
        <div className="flex-1 overflow-hidden flex flex-col lg:flex-row">
          {/* Match List Area */}
          <div className={`
            border-r border-slate-800 flex-col bg-slate-950/50 transition-all duration-300 ease-in-out overflow-hidden shrink-0
            ${selectedMatch ? 'hidden lg:flex' : 'flex'}
            ${matchListOpen ? 'w-full lg:w-96 opacity-100' : 'w-full lg:w-0 lg:border-r-0 lg:opacity-0'}
          `}>
            <div className="w-full lg:w-96 flex flex-col h-full">
              <div className="p-5 border-b border-slate-800 bg-slate-900/30 flex justify-between items-center shrink-0">
              <div>
                <h2 className="font-bold text-slate-200 text-sm tracking-wide">{selectedLeague.name}</h2>
                <p className="text-[10px] text-slate-500 font-mono mt-1 tracking-widest">
                  {data?.matches?.length || 0} MATCHS TROUVÉS
                </p>
              </div>
              {data && <div className="text-[10px] uppercase font-mono tracking-widest text-emerald-500 bg-emerald-500/10 px-2 py-1 rounded border border-emerald-500/20 shadow-inner">Synchronisé</div>}
            </div>
            
            <div className="flex-1 overflow-y-auto p-4 custom-scrollbar relative">
              {loading ? (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 text-slate-500 bg-slate-950/50 backdrop-blur-sm z-10">
                  <div className="w-5 h-5 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin"></div>
                  <span className="text-[10px] uppercase tracking-widest font-mono">Chargement de la Matrice...</span>
                </div>
              ) : error ? (
                <div className="p-4 border border-rose-500/30 bg-rose-500/10 rounded-xl text-rose-400 text-sm flex flex-col gap-2 shadow-inner">
                  <span className="font-bold uppercase tracking-wider text-xs">Erreur Système</span>
                  <span className="text-xs leading-relaxed opacity-90">{error}</span>
                </div>
              ) : (
                <MatchList 
                  matches={filteredMatches} 
                  selectedMatch={selectedMatch}
                  onSelectMatch={setSelectedMatch}
                />
              )}
            </div>
          </div>
          </div>

          {/* Match Dashboard Area */}
          <div className={`
            flex-1 overflow-y-auto bg-slate-950 custom-scrollbar
            ${!selectedMatch ? 'hidden lg:flex' : 'flex'}
          `}>
            {selectedMatch ? (
              <div className="p-4 lg:p-8">
                <button 
                  className="lg:hidden mb-6 text-xs font-bold uppercase tracking-widest text-slate-400 flex items-center gap-2 hover:text-slate-200 transition-colors bg-slate-900 px-4 py-2 rounded-lg border border-slate-800 w-full justify-center"
                  onClick={() => setSelectedMatch(null)}
                >
                  <X size={14} /> Fermer le tableau de bord
                </button>
                <MatchDashboard match={selectedMatch} />
              </div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-slate-500 gap-5 p-8 h-full">
                <div className="w-20 h-20 rounded-2xl bg-slate-900 border border-slate-800 flex items-center justify-center shadow-inner relative overflow-hidden">
                  <div className="absolute inset-0 bg-gradient-to-tr from-emerald-500/5 to-transparent"></div>
                  <Activity size={32} className="text-slate-700 relative z-10" />
                </div>
                <div className="text-center max-w-xs">
                  <p className="font-bold text-slate-400 uppercase tracking-widest text-sm mb-2">En attente de sélection</p>
                  <p className="text-xs text-slate-500 leading-relaxed font-mono">Sélectionnez un match depuis la matrice pour charger son tableau de bord de gestion des risques et ses probabilités réelles.</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
