import React, { useState, useEffect } from 'react';
import { Search, Terminal, Activity, Layers, Menu, X, Command, PanelLeftClose, PanelLeftOpen, ShieldCheck, Zap, Target, Lock, LineChart, Flame, TrendingUp } from 'lucide-react';
import { MatchList } from './components/MatchList';
import { MatchDashboard } from './components/MatchDashboard';
import teamMapping from '../team_mapping.json';

const LEAGUES = [
  { id: 'ALL', name: 'Toutes les Ligues', code: 'ALL', flag: '🌍' },
  { id: 'EDV', name: 'Eredivisie', code: 'EDV', flag: '🇳🇱' },
  { id: 'PL', name: 'Premier League', code: 'PL', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { id: 'POR1', name: 'Primeira Liga', code: 'POR1', flag: '🇵🇹' },
  { id: 'LIGA', name: 'LaLiga', code: 'LIGA', flag: '🇪🇸' },
  { id: 'LIG1', name: 'Ligue 1', code: 'LIG1', flag: '🇫🇷' },
  { id: 'BUND', name: 'Bundesliga', code: 'BUND', flag: '🇩🇪' },
  { id: 'SERIEA', name: 'Serie A', code: 'SERIEA', flag: '🇮🇹' },
];

export default function App() {
  const [selectedLeague, setSelectedLeague] = useState(LEAGUES[0]);
  const [selectedDate, setSelectedDate] = useState('ALL');
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedMatch, setSelectedMatch] = useState(null);
  const [sidebarOpen, setSidebarOpen] = useState(typeof window !== 'undefined' ? window.innerWidth >= 1024 : false);
  const [matchListOpen, setMatchListOpen] = useState(true);
  const [showTrueFavorites, setShowTrueFavorites] = useState(false);
  const [showSuperSignals, setShowSuperSignals] = useState(false);
  const [showHighConfidence, setShowHighConfidence] = useState(false);
  const [showUltraSafe, setShowUltraSafe] = useState(false);
  const [showRegularity, setShowRegularity] = useState(false);
  const [showSafeButs, setShowSafeButs] = useState(false);
  const [showTopForm, setShowTopForm] = useState(false);

  useEffect(() => {
    async function fetchData() {
      setLoading(true);
      setError(null);
      try {
        // 1. Load the dynamic index.json generated by our Vite plugin
        const indexResponse = await fetch('/data/index.json').catch(() => null);
        let availableFiles = [];
        if (indexResponse && indexResponse.ok) {
          availableFiles = await indexResponse.json();
        }

        // 2. Find matching files for the selected league
        const code = selectedLeague.code;
        
        let json = { matches: [] };
        
        if (code === 'ALL') {
          let allMatches = [];
          const leagueCodes = LEAGUES.filter(l => l.code !== 'ALL').map(l => l.code);
          
          const fetchPromises = leagueCodes.map(async (c) => {
            const matchingFiles = availableFiles.filter(f => f.includes(`-${c}_`));
            matchingFiles.sort().reverse();
            const targetFile = matchingFiles.length > 0 ? `/data/${matchingFiles[0]}` : `/data/LATEST_${c}.json`;
            try {
              const res = await fetch(targetFile);
              if (res.ok) {
                const data = await res.json();
                return data.matches || [];
              }
            } catch(e) {}
            return [];
          });
          
          const results = await Promise.all(fetchPromises);
          results.forEach(m => allMatches.push(...m));
          json.matches = allMatches;
        } else {
          const matchingFiles = availableFiles.filter(f => f.includes(`-${code}_`));
          matchingFiles.sort().reverse();
          const targetFile = matchingFiles.length > 0 ? `/data/${matchingFiles[0]}` : `/data/LATEST_${code}.json`;
          
          const response = await fetch(targetFile);
          if (!response.ok) {
            throw new Error(`Data matrix not found for ${selectedLeague.name}.`);
          }
          json = await response.json();
        }

        // Fetch matchups dynamically
        try {
          const matchupsIndexRes = await fetch('/data/matchups/index.json').catch(() => null);
          let allMatchups = [];
          
          if (matchupsIndexRes && matchupsIndexRes.ok) {
            const matchupFiles = await matchupsIndexRes.json();
            const fetchPromises = matchupFiles.map(async (file) => {
              const res = await fetch(`/data/matchups/${file}`);
              if (res.ok) {
                const data = await res.json();
                Object.values(data).forEach(arr => allMatchups.push(...arr));
              }
            });
            await Promise.all(fetchPromises);
          }

          const normalize = (str) => str.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim();
          
          const getAlias = (name) => {
            const mapped = teamMapping[name];
            if (mapped) return normalize(mapped);
            
            const norm = normalize(name);
            return norm;
          };

          if (json.matches) {
            json.matches.forEach(m => {
              const parts = m.Matchup.split(' vs ');
              if (parts.length === 2) {
                const homeTeamRaw = parts[0];
                const awayTeamRaw = parts[1];
                
                const homeAlias = getAlias(homeTeamRaw);
                const awayAlias = getAlias(awayTeamRaw);
                
                const found = allMatchups.find(mu => {
                  const muHome = getAlias(mu.home);
                  const muAway = getAlias(mu.away);
                  
                  // Check for direct alias match OR inclusion
                  const homeMatch = homeAlias === muHome || homeAlias.includes(muHome) || muHome.includes(homeAlias);
                  const awayMatch = awayAlias === muAway || awayAlias.includes(muAway) || muAway.includes(awayAlias);
                  
                  return homeMatch && awayMatch;
                });

                // FALLBACK: If still not found, try a very loose match on names
                let finalFound = found;
                if (!finalFound) {
                  finalFound = allMatchups.find(mu => {
                    const muHome = normalize(mu.home);
                    const muAway = normalize(mu.away);
                    return homeAlias.includes(muHome) || muHome.includes(homeAlias) || 
                           awayAlias.includes(muAway) || muAway.includes(awayAlias);
                  });
                }

                m.date = finalFound ? finalFound.date : 'Date Inconnue';
                m.hours = finalFound && finalFound.hours ? finalFound.hours : null;
                m.shortHome = finalFound ? finalFound.home : parts[0];
                m.shortAway = finalFound ? finalFound.away : parts[1];
              } else {
                m.date = 'Date Inconnue';
                m.hours = null;
                m.shortHome = m.Matchup;
                m.shortAway = '';
              }
            });
          }
        } catch (err) {
          console.error("Failed to merge dates:", err);
        }

        setData(json);
        setSelectedMatch(null);
      } catch (err) {
        console.error(err);
        setError(err.message);
        setData(null);
        setSelectedMatch(null);
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, [selectedLeague]);

  const availableDates = Array.from(new Set(data?.matches?.map(m => m.date || 'Date Inconnue') || [])).sort((a, b) => {
    if (a === 'Date Inconnue') return 1;
    if (b === 'Date Inconnue') return -1;
    return a.localeCompare(b);
  });

  const filteredMatches = data?.matches?.filter(match => {
    const textMatch = match.Matchup.toLowerCase().includes(searchQuery.toLowerCase());
    const dateMatch = selectedDate === 'ALL' || match.date === selectedDate;
    const isFalseFav = match.Risk_Management_Context?.Tactical_Red_Flags?.IS_FALSE_FAVORITE;
    const favMatch = !showTrueFavorites || isFalseFav === false;

    const hasSuperSignal = match.Super_Signals && Object.values(match.Super_Signals).some(v => v === true);
    const signalMatch = !showSuperSignals || hasSuperSignal;

    const confidence = match.Calibration_Diagnostics?.confidence_index || 0;
    const confidenceMatch = !showHighConfidence || confidence >= 0.65;

    const tension = match.Risk_Management_Context?.Team_Psychology?.net_justice_tension || 0;
    const hasData = match.Risk_Management_Context?.Tactical_Red_Flags?.MISSING_FOTMOB_DATA === false;
    const ultraSafeMatch = !showUltraSafe || (confidence >= 0.65 && isFalseFav === false && tension <= 5 && hasData);

    const trajH = match.Calibration_Diagnostics?.trajectory_home || 1;
    const trajA = match.Calibration_Diagnostics?.trajectory_away || 1;
    const isRegular = (1 - Math.abs(trajH - 1)) >= 0.99 && (1 - Math.abs(trajA - 1)) >= 0.99;
    const regularMatch = !showRegularity || isRegular;

    const openness = match.Risk_Management_Context?.Tactical_Red_Flags?.match_openness_index || 0;
    const safeButsMatch = !showSafeButs || (confidence >= 0.65 && openness >= 3.0 && hasData);

    const homeNarrative = match.Risk_Management_Context?.Situational_Narrative?.Home_Team || {};
    const awayNarrative = match.Risk_Management_Context?.Situational_Narrative?.Away_Team || {};
    
    const homeFotmob = match.Risk_Management_Context?.Tactical_Red_Flags?.fotmob_rating_home || 0;
    const awayFotmob = match.Risk_Management_Context?.Tactical_Red_Flags?.fotmob_rating_away || 0;
    const gap = match.Risk_Management_Context?.Tactical_Red_Flags?.team_rating_gap || 0;

    const homeIsTopForm = homeNarrative.momentum === 'HOT' && trajH >= 0.98 && (homeNarrative.performance_analysis?.actual_league_position || 99) <= 6 && homeFotmob >= 6.8 && gap > 0;
    const awayIsTopForm = awayNarrative.momentum === 'HOT' && trajA >= 0.98 && (awayNarrative.performance_analysis?.actual_league_position || 99) <= 6 && awayFotmob >= 6.8 && gap < 0;
    const topFormMatch = !showTopForm || homeIsTopForm || awayIsTopForm;

    return textMatch && dateMatch && favMatch && signalMatch && confidenceMatch && ultraSafeMatch && regularMatch && safeButsMatch && topFormMatch;
  }) || [];

  return (
    <div className="flex h-screen overflow-hidden bg-slate-950 text-slate-200">
      {/* Mobile Sidebar Overlay */}
      {sidebarOpen && (
        <div 
          className="fixed inset-0 bg-black/60 z-30 lg:hidden backdrop-blur-sm transition-opacity"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      {/* Sidebar (Leagues Menu) */}
      <aside className={`
        fixed lg:static inset-y-0 left-0 z-40
        bg-slate-900 border-slate-800 flex flex-col
        transition-all duration-300 ease-in-out shadow-2xl lg:shadow-none
        ${sidebarOpen 
          ? 'translate-x-0 w-52 border-r opacity-100' 
          : '-translate-x-full lg:translate-x-0 w-52 lg:w-0 border-r lg:border-r-0 opacity-100 lg:opacity-0 lg:overflow-hidden'}
      `}>
        <div className="p-5 flex items-center gap-3 border-b border-slate-800 bg-slate-900/50">
          <div className="bg-emerald-500/10 p-2 rounded-lg border border-emerald-500/20 shadow-inner">
            <Terminal className="text-emerald-400" size={20} />
          </div>
          <div>
            <h1 className="font-bold text-sm text-slate-100 tracking-wide">ColdBetdrox Lab</h1>
            <p className="text-[10px] text-slate-500 font-mono tracking-widest uppercase">Terminal v7.6.1</p>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
          <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-3 px-2">Matrices Actives</div>
          <nav className="flex flex-col gap-1.5">
            {LEAGUES.map(league => (
              <button
                key={league.id}
                onClick={() => {
                  setSelectedLeague(league);
                  setMatchListOpen(true); // Ensure match list is open when switching leagues
                }}
                className={`
                  flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm transition-all text-left
                  ${selectedLeague.id === league.id 
                    ? 'bg-slate-800 text-emerald-400 font-medium shadow-sm ring-1 ring-slate-700/50' 
                    : 'text-slate-400 hover:bg-slate-800/50 hover:text-slate-200'}
                `}
              >
                <span className="text-lg">{league.flag}</span>
                {league.name}
              </button>
            ))}
          </nav>
        </div>
        
        <div className="p-4 border-t border-slate-800 flex flex-col gap-1">
          <div className="flex items-center gap-2 text-[10px] text-slate-500 font-mono">
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></div>
            SYSTÈME EN LIGNE
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col min-w-0 bg-slate-950 overflow-y-auto lg:overflow-hidden">
        {/* Header */}
        <header className="h-16 border-b border-slate-800 bg-slate-900/80 backdrop-blur-md flex items-center justify-between px-4 lg:px-6 sticky top-0 z-20">
          <div className="flex items-center gap-4">
            <button 
              className="text-slate-400 hover:text-slate-200 transition-colors bg-slate-800 p-2 rounded-lg border border-slate-700"
              onClick={() => setSidebarOpen(!sidebarOpen)}
              title={sidebarOpen ? "Masquer les ligues" : "Afficher les ligues"}
            >
              <Menu size={18} />
            </button>
            <button 
              className="hidden lg:flex text-slate-400 hover:text-slate-200 transition-colors bg-slate-900 p-2 rounded-lg border border-slate-800"
              onClick={() => setMatchListOpen(!matchListOpen)}
              title={matchListOpen ? "Masquer la liste des matchs" : "Afficher la liste des matchs"}
            >
              {matchListOpen ? <PanelLeftClose size={18} /> : <PanelLeftOpen size={18} />}
            </button>
            <div className="hidden lg:flex items-center gap-2 text-xs text-slate-400 font-medium uppercase tracking-widest bg-slate-900 px-3 py-1.5 rounded-lg border border-slate-800">
              <Activity size={14} className="text-emerald-500" />
              <span>Engine <span className="text-emerald-400 font-mono ml-1">ACTIVE</span></span>
            </div>
          </div>

          <div className="flex-1 flex items-center justify-end gap-2 sm:gap-3 ml-2 sm:ml-4 min-w-0">
            <div className="relative group w-full max-w-[180px] hidden md:block shrink-0">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500 group-focus-within:text-emerald-500 transition-colors" size={16} />
              <input 
                type="text" 
                placeholder="Filtrer..."
                value={searchQuery}
                onChange={e => setSearchQuery(e.target.value)}
                className="w-full bg-slate-950 border border-slate-700 rounded-lg py-1.5 pl-9 pr-3 text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 transition-all font-mono"
              />
            </div>
            <select 
              value={selectedDate}
              onChange={e => setSelectedDate(e.target.value)}
              className="bg-slate-950 border border-slate-700 rounded-lg py-1.5 px-2 sm:px-3 text-xs sm:text-sm text-slate-400 focus:outline-none focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 transition-all font-mono appearance-none shrink-0 cursor-pointer"
            >
              <option value="ALL">Toutes les dates</option>
              {availableDates.map(date => {
                let displayDate = date;
                if (date !== 'Date Inconnue') {
                  const d = new Date(`${date}T12:00:00`);
                  displayDate = d.toLocaleDateString('fr-FR', { weekday: 'short', day: 'numeric', month: 'short' });
                  displayDate = displayDate.charAt(0).toUpperCase() + displayDate.slice(1);
                }
                return (
                  <option key={date} value={date}>
                    {displayDate}
                  </option>
                );
              })}
            </select>
            
            <div className="flex gap-1.5 sm:gap-2 overflow-x-auto pb-1 min-w-0 custom-scrollbar snap-x">
              <button
                onClick={() => setShowTrueFavorites(!showTrueFavorites)}
                className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs transition-all font-mono border shrink-0 snap-start ${
                  showTrueFavorites 
                    ? 'bg-emerald-500/10 border-emerald-500/50 text-emerald-400 shadow-[0_0_10px_rgba(16,185,129,0.2)]' 
                    : 'bg-slate-950 border-slate-700 text-slate-400 hover:text-slate-200 hover:bg-slate-900'
                }`}
                title="Vrais Favoris"
              >
                <ShieldCheck size={14} />
                <span className="hidden xl:inline">Favoris</span>
              </button>
              
              <button
                onClick={() => setShowSuperSignals(!showSuperSignals)}
                className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs transition-all font-mono border shrink-0 snap-start ${
                  showSuperSignals 
                    ? 'bg-amber-500/10 border-amber-500/50 text-amber-400 shadow-[0_0_10px_rgba(245,158,11,0.2)]' 
                    : 'bg-slate-950 border-slate-700 text-slate-400 hover:text-slate-200 hover:bg-slate-900'
                }`}
                title="Super Signaux (Elite)"
              >
                <Zap size={14} />
                <span className="hidden xl:inline">Elite</span>
              </button>
              
              <button
                onClick={() => setShowHighConfidence(!showHighConfidence)}
                className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs transition-all font-mono border shrink-0 snap-start ${
                  showHighConfidence 
                    ? 'bg-blue-500/10 border-blue-500/50 text-blue-400 shadow-[0_0_10px_rgba(59,130,246,0.2)]' 
                    : 'bg-slate-950 border-slate-700 text-slate-400 hover:text-slate-200 hover:bg-slate-900'
                }`}
                title="Haute Confiance (>65%)"
              >
                <Target size={14} />
                <span className="hidden xl:inline">Confiance</span>
              </button>

              <button
                onClick={() => setShowUltraSafe(!showUltraSafe)}
                className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs transition-all font-mono border shrink-0 snap-start ${
                  showUltraSafe 
                    ? 'bg-purple-500/10 border-purple-500/50 text-purple-400 shadow-[0_0_10px_rgba(168,85,247,0.2)]' 
                    : 'bg-slate-950 border-slate-700 text-slate-400 hover:text-slate-200 hover:bg-slate-900'
                }`}
                title="Safe Pick 95% (Confiance > 65% + Vrai Favori + Tension Basse)"
              >
                <Lock size={14} />
                <span className="hidden xl:inline">Safe Pick</span>
              </button>

              <button
                onClick={() => setShowRegularity(!showRegularity)}
                className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs transition-all font-mono border shrink-0 snap-start ${
                  showRegularity 
                    ? 'bg-cyan-500/10 border-cyan-500/50 text-cyan-400 shadow-[0_0_10px_rgba(6,182,212,0.2)]' 
                    : 'bg-slate-950 border-slate-700 text-slate-400 hover:text-slate-200 hover:bg-slate-900'
                }`}
                title="Haute Régularité (Trajectoire > 99% pour les deux équipes)"
              >
                <LineChart size={14} />
                <span className="hidden xl:inline">Régularité</span>
              </button>

              <button
                onClick={() => setShowSafeButs(!showSafeButs)}
                className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs transition-all font-mono border shrink-0 snap-start ${
                  showSafeButs 
                    ? 'bg-orange-500/10 border-orange-500/50 text-orange-400 shadow-[0_0_10px_rgba(249,115,22,0.2)]' 
                    : 'bg-slate-950 border-slate-700 text-slate-400 hover:text-slate-200 hover:bg-slate-900'
                }`}
                title="Safe Buts (Confiance > 65% + Openness > 3.0)"
              >
                <Flame size={14} />
                <span className="hidden xl:inline">Safe Buts</span>
              </button>

              <button
                onClick={() => setShowTopForm(!showTopForm)}
                className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs transition-all font-mono border shrink-0 snap-start ${
                  showTopForm 
                    ? 'bg-pink-500/10 border-pink-500/50 text-pink-400 shadow-[0_0_10px_rgba(236,72,153,0.2)]' 
                    : 'bg-slate-950 border-slate-700 text-slate-400 hover:text-slate-200 hover:bg-slate-900'
                }`}
                title="Top Forme (Elite Top 6 + HOT + Trajectoire > 0.98 + FotMob > 6.8 + Avantage Gap)"
              >
                <TrendingUp size={14} />
                <span className="hidden xl:inline">Top Forme</span>
              </button>
            </div>
          </div>
        </header>

        {/* Content Area */}
        <div className="flex-1 flex flex-col lg:flex-row overflow-visible lg:overflow-hidden">
          {/* Match List Area */}
          <div className={`
            border-r border-slate-800 flex-col bg-slate-950/50 transition-all duration-300 ease-in-out overflow-hidden shrink-0
            ${selectedMatch ? 'hidden lg:flex' : 'flex'}
            ${matchListOpen ? 'w-full lg:w-80 opacity-100' : 'w-full lg:w-0 lg:border-r-0 lg:opacity-0'}
          `}>
            <div className="w-full lg:w-80 flex flex-col h-full min-h-[500px] lg:min-h-0">
              <div className="p-5 border-b border-slate-800 bg-slate-900/30 flex justify-between items-center shrink-0">
              <div>
                <h2 className="font-bold text-slate-200 text-sm tracking-wide">{selectedLeague.name}</h2>
                <p className="text-[10px] text-slate-500 font-mono mt-1 tracking-widest">
                  {data?.matches?.length || 0} MATCHS TROUVÉS
                </p>
              </div>
              {data && <div className="text-[10px] uppercase font-mono tracking-widest text-emerald-500 bg-emerald-500/10 px-2 py-1 rounded border border-emerald-500/20 shadow-inner">Synchronisé</div>}
            </div>
            
            <div className="flex-1 overflow-y-auto p-4 custom-scrollbar relative">
              {loading ? (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 text-slate-500 bg-slate-950/50 backdrop-blur-sm z-10">
                  <div className="w-5 h-5 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin"></div>
                  <span className="text-[10px] uppercase tracking-widest font-mono">Chargement de la Matrice...</span>
                </div>
              ) : error ? (
                <div className="p-4 border border-rose-500/30 bg-rose-500/10 rounded-xl text-rose-400 text-sm flex flex-col gap-2 shadow-inner">
                  <span className="font-bold uppercase tracking-wider text-xs">Erreur Système</span>
                  <span className="text-xs leading-relaxed opacity-90">{error}</span>
                </div>
              ) : (
                <MatchList 
                  matches={filteredMatches} 
                  selectedMatch={selectedMatch}
                  onSelectMatch={(match) => {
                    setSelectedMatch(match);
                    setSidebarOpen(false); // Rule: Leagues menu disappears automatically when match is selected
                  }}
                />
              )}
            </div>
          </div>
          </div>

          {/* Match Dashboard Area */}
          <div className={`
            flex-1 overflow-y-auto lg:overflow-y-auto bg-slate-950 custom-scrollbar
            ${!selectedMatch ? 'hidden lg:flex' : 'flex'}
          `}>
            {selectedMatch ? (
              <div className="p-4 lg:p-8 pb-24 lg:pb-8 w-full">
                <button 
                  className="lg:hidden mb-6 text-xs font-bold uppercase tracking-widest text-slate-400 flex items-center gap-2 hover:text-slate-200 transition-colors bg-slate-900 px-4 py-2 rounded-lg border border-slate-800 w-full justify-center"
                  onClick={() => setSelectedMatch(null)}
                >
                  <X size={14} /> Fermer le tableau de bord
                </button>
                <MatchDashboard match={selectedMatch} />
              </div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-slate-500 gap-5 p-8 h-full">
                <div className="w-20 h-20 rounded-2xl bg-slate-900 border border-slate-800 flex items-center justify-center shadow-inner relative overflow-hidden">
                  <div className="absolute inset-0 bg-gradient-to-tr from-emerald-500/5 to-transparent"></div>
                  <Activity size={32} className="text-slate-700 relative z-10" />
                </div>
                <div className="text-center max-w-xs">
                  <p className="font-bold text-slate-400 uppercase tracking-widest text-sm mb-2">En attente de sélection</p>
                  <p className="text-xs text-slate-500 leading-relaxed font-mono">Sélectionnez un match depuis la matrice pour charger son tableau de bord de gestion des risques et ses probabilités réelles.</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
